# Generated by Django 2.1.3 on 2018-11-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('firstName', models.CharField(blank=True, max_length=255)),
                ('lastName', models.CharField(blank=True, max_length=255)),
                ('phoneNumber', models.BigIntegerField(blank=True)),
                ('dateOfBirth', models.DateField(blank=True)),
                ('street1', models.TextField(blank=True)),
                ('street2', models.TextField(blank=True)),
                ('street3', models.TextField(blank=True)),
                ('state', models.TextField(blank=True)),
                ('zip', models.IntegerField(blank=True)),
                ('country', models.TextField(blank=True)),
            ],
        ),
    ]
